### PR TITLE
initial: mostly complete example

### PR DESCRIPTION
**Pull request by volodymyrss**
this should be an essentially functional (slightly reduced) example; please make any suggestions for structure and so.

### CODE REVIEW

**Comment by volodymyrss** [comment]
for some reason after `pip install reana-client` the validation did not work, with an obscure message "something went wrong", even with -lDEBUG. Only using master branch version worked.

**Comment by tiborsimko** [comment]
Some comments:

**(1) Running the example**

I have tried to run the analysis, but I get an error due to:

```
2020-01-10 10:29:36,986 - papermill - INFO - Executing Cell 8---------------------------------------
2020-01-10 10:29:37,210 - papermill - INFO - 198700430010.001,198700440010.001,198700450010.001,198700460010.001,198700470010.001,198700480010.001,198700490010.001,198700500010.001,198700510010.001,198700520010.001
waiting for remote response, please wait run_analysis http://cdcihn.isdc.unige.ch/staging-1.2/dispatcher
...
SystemExit: RemoteException (line 58): remote/connection error, server response is not valid, check your credentials and connection status
 exception message: HTTPConnectionPool(host='cdcihn.isdc.unige.ch', port=80): Max retries exceeded with url: /staging-1.2/dispatcher/run_analysis?osa_version=xxxx
 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa7b8f3edd8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

Is the example only runnable inside the UniGe network? Does it need to contact ISDC?  It would be great if the example would be runnable "anywhere", that is if the data would be publicly accessible... Perhaps at least for the given set of inputs.

**(2) Environment**

The example uses Docker image `cdci/crab-integral-verification:0.1.0-1-g1f9ce94-root` currently. Have you thought of using this image in a R/O manner, i.e. the example code will simply use it, or have you thought of also creating the environment in a R/W manner from within the example sources?  If so, we'd need the full image creation reproducible recipe.

For example, there is 'code/Dockerfile' but e.g. it relies on "repo" being available, which is not coming with the example.  Shall we move `code/Dockerfile` into 'environment/Dockerfile' and work on packaging the environment there?

**(3) Cosmetics**

- The workflow run names in `Makefile` do not have to be auto-generated in that way, e.g. you can always pass the name "crab" and the workflow will create "crab.1", "crab.2", "crab.3" with incrementally-increasing "run number". I.e. the random ID auto-generation is not necessary.

- Now that REANA v0.6.0 was released, we can pip-install that instead of the bleeding edge versions in CI.  Ideally the demo examples run with any reana-client version, latest stable release should be fine.

- We can fix small things like this at the merge time once the example is running.

**(4) Note**

BTW when the example fails I'm seeing:

```console
$ reana-client status -w crab
NAME   RUN_NUMBER   CREATED               STATUS   PROGRESS
crab   1            2020-01-10T10:26:14   failed   1/-1
```

Interesting the "-1" step number... We'll see about fixing this internally.

**Comment by volodymyrss** [comment]
> Some comments:
> 
> **(1) Running the example**
> 
> I have tried to run the analysis, but I get an error due to:
>  ...

It should not be limited to UniGE, there is a public endpoint (somewhat limited but sufficient for this purpose)
But the container was built with internal notebook. Sorry for that.

> 
> **(2) Environment**
> 
> The example uses Docker image `cdci/crab-integral-verification:0.1.0-1-g1f9ce94-root` currently. Have you thought of using this image in a R/O manner, i.e. the example code will simply use it, or have you thought of also creating the environment in a R/W manner from within the example sources? If so, we'd need the full image creation reproducible recipe.

I added "make build" option, it should also make issues like (1) more approachable.

I am not sure right now if I should autofill image tag (which is otherwise derived from the example revision) in the .cwl . What do you think?

> 
> For example, there is 'code/Dockerfile' but e.g. it relies on "repo" being available, which is not coming with the example. Shall we move `code/Dockerfile` into 'environment/Dockerfile' and work on packaging the environment there?

"repo" is in principle already inside, it just contains the notebook.
I made the build process directly usable.

> 
> **(3) Cosmetics**
> 
> * The workflow run names in `Makefile` do not have to be auto-generated in that way, e.g. you can always pass the name "crab" and the workflow will create "crab.1", "crab.2", "crab.3" with incrementally-increasing "run number". I.e. the random ID auto-generation is not necessary.

I saw this auto-increment and this is precisely why I made a custom name, to explicitly refer to the job - otherwise every once in a while I needed to lookup which is the run name used.

This approach is not really used in the example so it does not matter, I changed it to the default autoincrement.

> * Now that REANA v0.6.0 was released, we can pip-install that instead of the bleeding edge versions in CI.  Ideally the demo examples run with any reana-client version, latest stable release should be fine.
> * We can fix small things like this at the merge time once the example is running.

I installed REANA cluster v0.6.0 and it seems all ok, except for this issue that already happened before:

```
job: 
 mkdir: cannot create directory '/var/reana/users/00000000-0000-0000-0000-000000000000/workflows/c90743b6-487c-4e25-966c-5cf44616c6a9/cwl': Permission denied
```

It happens sometimes when cwl job is running on a different node than the controller and engine. Is there a recommended solution for this? I remember it could be solved with shared cephfs, but not nfs?

**Comment by tiborsimko** [comment]
Thanks for the update, the example now works for me :+1: with the following amendment:

-  I'm using `latest` image everywhere. In your branch, the `IMAGE` is dynamically generated in `Makefile`, which is OK, but to make this truly work for N developers, we'd have to amend `workflow/cwl/crab.cwl` as well to use the same image tag that was auto-generated in `Makefile`. However, the git commit SHA1 are certainly different for each developer, so we cannot easily do this... at least not without putting some kind of templating into `crab.cwl`.  Hence I simply used `reanahub/reana-demo-cdci-crab-pulsar-integral-verification:latest` both in `Makefile` and in `workflow/cwl/crab.cwl` and everything works.

If you are OK with moving tags to `latest` in this way in the `master` branch, I can squash and merge and we can make further improvements to the example (e.g. see some comments below) later? Please tell me whether it would be OK with you?   

Some comments to the notebook outputs:

- The outputs are as follows:

```
$ reana-client ls -w crab
NAME                                            SIZE     LAST-MODIFIED
inputs.json                                     113      2020-01-13T13:06:52
workflow.json                                   1364     2020-01-13T13:06:52
cwl/docker_outdir/crab_output.html              571148   2020-01-13T13:09:36
cwl/docker_outdir/crab_output.ipynb             320500   2020-01-13T13:09:31
cwl/docker_outdir/cwl.output.json               33022    2020-01-13T13:09:31
cwl/docker_outdir/crab_output.json              33022    2020-01-13T13:09:31
cwl/docker_outdir/data/default-cache/cache.db   10240    2020-01-13T13:07:18
```

- Inside `crab_output.html`, I can see data and folded model fit figures. Would it be possible to amend the notebook to also create PNG images of resulting plots directly by calling `savefig`?  We do it here  https://github.com/reanahub/reana-demo-worldpopulation/blob/master/code/worldpopulation.ipynb We could do this after merge, but if your non-figure crab outputs are also important, then it is perhaps not even worth.

- It would be nice to silence some errors as it could scare some users, e.g. I'm seeing:

```
unable to setup logstash FileNotFoundError(2, 'No such file or directory')
unable to setup logstash FileNotFoundError(2, 'No such file or directory')
big problem with sentry: FileNotFoundError(2, 'No such file or directory')
```

- There are also some FITS warnings, but this is just cosmetics, not important:

```
WARNING: VerifyWarning: Keyword name 'instrument' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING: VerifyWarning: Keyword name 'osa_version' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING: VerifyWarning: Keyword name 'product_type' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING: VerifyWarning: Keyword name 'query_status' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING: VerifyWarning: Keyword name 'query_type' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING: VerifyWarning: Keyword name 'session_id' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
```

Some comments to your questions:

- The write permission problem is indeed good to solve via NFS share, regarding the share name it must be "manila...cephfs..." as we suppose this name in reana-cluster; however the share itself can be perfectly well created as NFS.  This is what Ben does in https://bengalewsky.github.io/openstack/reana/hep/scailfin/2019/01/24/ZeroToReanaOnOpenstack.html

- We have recently moved to Helm in the `master` branch, so the installation process will be much simplified.  We'll document how to create shares and deploy REANA with Helm.  Until then your fix is perfect.

**Comment by volodymyrss** [comment]
> Thanks for the update, the example now works for me  with the following amendment:
> 
> * I'm using `latest` image everywhere. In your branch, the `IMAGE` is dynamically generated in `Makefile`, which is OK, but to make this truly work for N developers, we'd have to amend `workflow/cwl/crab.cwl` as well to use the same image tag that was auto-generated in `Makefile`. However, the git commit SHA1 are certainly different for each developer, so we cannot easily do this... at least not without putting some kind of templating into `crab.cwl`.  Hence I simply used `reanahub/reana-demo-cdci-crab-pulsar-integral-verification:latest` both in `Makefile` and in `workflow/cwl/crab.cwl` and everything works.

this was my question above (in the previous reply): should I auto-fill the image tag?
Technically, I auto-generate the cwl from the notebook (it's parametrized with papermill, and hence contains all necessary information). In this repository, I did not add this function and added just the product cwl. So another solution is needed, at this point.

There are some issues with "latest", for example it means that by running the same exact cwl I get a different result - not very reproducible. 
Or am I missing something?
But for the purposes of the example, I do not mind either way.

> 
> If you are OK with moving tags to `latest` in this way in the `master` branch, I can squash and merge and we can make further improvements to the example (e.g. see some comments below) later? Please tell me whether it would be OK with you?

It's OK!

 
 
> * Inside `crab_output.html`, I can see data and folded model fit figures. Would it be possible to amend the notebook to also create PNG images of resulting plots directly by calling `savefig`?  We do it here  https://github.com/reanahub/reana-demo-worldpopulation/blob/master/code/worldpopulation.ipynb We could do this after merge, but if your non-figure crab outputs are also important, then it is perhaps not even worth.

The pictures are already stored in cwl.output.json - I understand that's the valid cwl output, the rest is just something produced along.

I added example for extraction of the png files in here b4cf6be89b .

The output notebook and conversion to html is stored for debug purposes, it's not listed in the cwl outputs.

> * It would be nice to silence some errors as it could scare some users, e.g. I'm seeing:
> 
> ```
> unable to setup logstash FileNotFoundError(2, 'No such file or directory')
> unable to setup logstash FileNotFoundError(2, 'No such file or directory')
> big problem with sentry: FileNotFoundError(2, 'No such file or directory')
> ```
> 
> * There are also some FITS warnings, but this is just cosmetics, not important:
> ...

That's mostly dependencies, I will see to suppress them.

> 
> Some comments to your questions:
> 
> * The write permission problem is indeed good to solve via NFS share, regarding the share name it must be "manila...cephfs..." as we suppose this name in reana-cluster; however the share itself can be perfectly well created as NFS.  This is what Ben does in https://bengalewsky.github.io/openstack/reana/hep/scailfin/2019/01/24/ZeroToReanaOnOpenstack.html
> * We have recently moved to Helm in the `master` branch, so the installation process will be much simplified.  We'll document how to create shares and deploy REANA with Helm.  Until then your fix is perfect.

thanks, sounds good!

as of now, from v0.6.0 all the rest seems to work well, I am starting to use it for some more substantial production computations. 
I did not yet try the SLURM compute backend, it seems complete in this version?

**Comment by tiborsimko** [comment]
@volodymyrss Thanks for the `download` target, I had to amend it slightly regarding pipe syntax (from `$(shell < cwl/docker_outdir/cwl.output.json jq -` to `$(shell cat cwl/docker_outdir/cwl.output.json | jq `), it works well.

Regrading `latest`, indeed it is not ideal, but the primary target of demo examples is the REANA audience that will basically run it in R/O mode initially, so using pre-ready `latest` seems OK.  We'd also need to parametrise Docker Hub organisation (e.g. use person's name) for this to work fully automatically.  BTW your approach of generating CWL from notebook is cool!  Another option could be to pass Docker image tag and Docker Hub organisation to CWL as options, but we can amend this afterwards.  For now let's merge with `latest`.

Regarding SLURM, yes it is fully complete, but some of the options are hard-coded in the component, e.g. SLURM_HOSTNAME specifies where to connect, by default `hpc-batch.cern.ch`.  These variables are not exposed to end users, so there is no way to put them into `reana.yaml` for now, so you would have to recompile the `reana-job-controller` image with modified sources specifying your SLURM instance.  Or you could create a new `slurmcdci_job_manager.py` subclass where you would override everything necessary, and we could have this in the REANA upstream sources.  This would be suitable especially if you need to plug a lot of custom code.  If you would only  need to specify which SLURM headnode to connect to, and which queue to use, etc, then we could solve these elegantly via reana.yaml configuration parameters.

**Comment by volodymyrss** [comment]
Great, thanks @tiborsimko! 
What would be the course of action now, what should I do?
For example, should I try to create the README similar to other examples?
Should we make issues to capture these plans?

**Comment by tiborsimko** [comment]
@volodymyrss Yes, I was planning to create a few issues for the remaining prettifications, I can do that later today

**Pull request merged**
